version: "3.9"
services:
  api:
    env_file: .env
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./services/api:/code
      - ./services/contrib:/contrib
      - ./locale:/locale
      - ./bin/compilemessages:/usr/bin/compilemessages
    command: bash -c "compilemessages && uvicorn api.run:app --reload --host 0.0.0.0"
    ports:
      - "8000:8000"
    depends_on:
      - redis
  rpc:
    env_file: .env
    container_name: rpc
    build:
      context: .
      dockerfile: Dockerfile.rpc
    volumes:
      - ./services/rpc:/code
    command: gunicorn run:web_app --bind 0.0.0.0:8080 --reload --worker-class aiohttp.GunicornWebWorker
    depends_on:
      - redis
  redis:
    container_name: redis
    image: "redis:alpine"
    volumes:
    - ./data/redis:/data