version: "3.9"
services:
  api:
    env_file: .env
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./services:/code
    command: uvicorn api.run:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    container_name: redis
    image: "redis:alpine"
    volumes:
    - ./data/redis:/data